openapi: '3.0.2'
info:
  title: Dalilah Resto
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
paths:
  /users:
    post:
      summary: crear un usuario nuevo
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  userName:
                    type: string
                  fullName:
                    type: string
                  email:
                    type: string
                  movil:
                    type: integer
                  adress:
                    type: string
                  password:
                    type: string
                  admin:
                    type: boolean
          description: datos para crear usuario
      responses:
        '200':
          description: 'usuario cargado con exito'
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
          